### ISSUE TITLE
Global_position error

### ISSUE THREAD

**Issue by ozcangezen** [michaelmalaska/aarpg-tutorial#1]
First of all, I want to show my gratitude for this godot learning series. It's going very well and then Lets get to the point.I was recevied that error at E25 Boomerang in min. 28:45 ( until this point everything worked well)
 when I throw boomerang, it's successfully starts to fly air but when the acc. get zero ( I mean the instantenous point that boomerang velocity 0 and then it should be return back) but at that point I've get error : Invalid access to property or key 'global_position' on a base object type of Nil and highlights the code direction = global_position.direction_to( player.global_position) in [boomerang.gd](javascript:void(0);) script. In Stack trace screen (debugger) Filter Stack Variables section I saw bunch of properties speed, state, direction and top of that I saw self and also self have object ID and bottom of self I saw player and equals to <null> . I highly suspect that because of this I've get error. Do you have any suggest this rookie ? Thanks a lot <3 for all of ur effort.

For better express, I've also added screenshot 
![godot_error_E25_boomerang](https://github.com/user-attachments/assets/5bc32085-35b1-413e-9216-789dd9bf1a7e)

Best Regards, Ozcan

**Comment by michaelmalaska** [comment]
Yeah, your player is _null_, meaning you don't have a reference to it...

My first thought it to check your ready function and make sure you are assigning the player variable like so:
![image](https://github.com/user-attachments/assets/040b2837-a48b-4029-8e79-c6f84d6be53f)

If that doesn't work, or just for fun, you can change your code on line 32 to read like this:

`direction = global_position.direction_to( PlayerManager.player.global_position )`

If either of those don't work you _should_ see a new/different error. Give that a go and report back :)

-- Michael

**Comment by ozcangezen** [comment]
yes sensei now everythings work well. I've adjusted the player.global_position to PlayerManager.player.global_position in both line 32 and 35. Also checked ready function but I have not adjust anything its same as training codes. Thanks for your fast response and time, I am really appreciated for all of your effort again 
![image](https://github.com/user-attachments/assets/fe1114b7-b9b2-4be7-8882-60faa09f0277)
